from sqlmodel import Session
from datetime import datetime, timedelta
from app.database import engine
from app.models import Deal

deals = [
    {
        "title": "AI Writer Pro",
        "description": "Generador de contenido con IA para blogs, emails y redes sociales.",
        "price": 12.50,
        "url": "https://example.com/ai-writer",
        "category": "IA",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 40,
        "coupon_code": "AI40",
        "popularity": 120,
    },
    {
        "title": "SEO Booster 3000",
        "description": "Auditorías automáticas, análisis de keywords y tracking de posiciones.",
        "price": 19.00,
        "url": "https://example.com/seo-booster",
        "category": "SEO",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 30,
        "coupon_code": "SEO30",
        "popularity": 95,
    },
    {
        "title": "Marketing Suite X",
        "description": "Automatización de marketing con funnels, emails y analíticas.",
        "price": 49.00,
        "url": "https://example.com/marketing-suite",
        "category": "Marketing",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 50,
        "coupon_code": "MARK50",
        "popularity": 180,
    },
    {
        "title": "Hosting Turbo Pro",
        "description": "Hosting ultrarrápido con CDN global y SSL incluido.",
        "price": 29.99,
        "url": "https://example.com/hosting-pro",
        "category": "Hosting",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 20,
        "coupon_code": "HOST20",
        "popularity": 140,
    },
    {
        "title": "Productividad Max",
        "description": "Notas, tareas, calendario inteligente y automatizaciones.",
        "price": 9.99,
        "url": "https://example.com/productividad-max",
        "category": "Productividad",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 10,
        "coupon_code": "PROD10",
        "popularity": 60,
    },
    {
        "title": "AI Image Studio",
        "description": "Generador de imágenes con IA estilo Midjourney.",
        "price": 14.99,
        "url": "https://example.com/ai-image",
        "category": "IA",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 35,
        "coupon_code": "IMG35",
        "popularity": 210,
    },
    {
        "title": "Keyword Miner Pro",
        "description": "Herramienta avanzada para encontrar keywords de alta intención.",
        "price": 17.99,
        "url": "https://example.com/keyword-miner",
        "category": "SEO",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 25,
        "coupon_code": "KEY25",
        "popularity": 130,
    },
    {
        "title": "Email Automator",
        "description": "Automatización de emails con IA y segmentación inteligente.",
        "price": 22.00,
        "url": "https://example.com/email-automator",
        "category": "Marketing",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 45,
        "coupon_code": "MAIL45",
        "popularity": 160,
    },
    {
        "title": "Cloud Storage Pro",
        "description": "Almacenamiento en la nube con cifrado y backups automáticos.",
        "price": 5.99,
        "url": "https://example.com/cloud-pro",
        "category": "Hosting",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 15,
        "coupon_code": "CLOUD15",
        "popularity": 80,
    },
    {
        "title": "TaskFlow",
        "description": "Gestor de tareas con IA y automatización de workflows.",
        "price": 11.99,
        "url": "https://example.com/taskflow",
        "category": "Productividad",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 50,
        "coupon_code": "TASK50",
        "popularity": 200,
    },
    {
        "title": "AI Chat Assistant",
        "description": "Chatbot con IA para atención al cliente y ventas.",
        "price": 24.99,
        "url": "https://example.com/ai-chat",
        "category": "IA",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 30,
        "coupon_code": "CHAT30",
        "popularity": 175,
    },
    {
        "title": "SEO Rank Tracker",
        "description": "Monitoriza tus posiciones en Google en tiempo real.",
        "price": 15.00,
        "url": "https://example.com/rank-tracker",
        "category": "SEO",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 20,
        "coupon_code": "RANK20",
        "popularity": 110,
    },
    {
        "title": "Sales Funnel Builder",
        "description": "Crea funnels de venta sin código.",
        "price": 39.00,
        "url": "https://example.com/funnel-builder",
        "category": "Marketing",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 60,
        "coupon_code": "FUNNEL60",
        "popularity": 250,
    },
    {
        "title": "Ultra Hosting SSD",
        "description": "Hosting SSD NVMe con uptime del 99.99%.",
        "price": 7.99,
        "url": "https://example.com/ultra-hosting",
        "category": "Hosting",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 35,
        "coupon_code": "SSD35",
        "popularity": 145,
    },
    {
        "title": "Focus Pro",
        "description": "App de productividad con bloqueo de distracciones.",
        "price": 4.99,
        "url": "https://example.com/focus-pro",
        "category": "Productividad",
        "image_url": "/static/uploads/hosting.jpg",
        "discount_percent": 25,
        "coupon_code": "FOCUS25",
        "popularity": 90,
    },
]

with Session(engine) as session:
    for d in deals:
        deal = Deal(
            **d,
            created_at=datetime.utcnow() - timedelta(days=1)
        )
        session.add(deal)
    session.commit()

print("15 deals ULTRA insertados correctamente.")
